language: node_js
node_js:
  - "8.10"
before_deploy:
  - echo "***** RUNNING BUILD ******"
  - yarn build
  - echo "***** FINISHED BUILD ******"
deploy:
  provider: s3
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  bucket: "eplazini"
  skip_cleanup: true
  local_dir: build