language: node_js
node_js:
  - "8.10"
scripts:
  - yarn build
deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "https://s3.console.aws.amazon.com/s3/buckets/eplazini"
  skip_cleanup: true
  local_dir: build